/* This file was automatically generated.  Do not edit! */
void open_default();
void open_path(char *path);
void destroy_device();
void create_device();
void setup_joystick_right_events();
void setup_joystick_left_events();
void setup_menupad_events();
void setup_gamepad_north();
void setup_gamepad_west();
void setup_gamepad_east();
void setup_gamepad_south();
void setup_dpad_events();
void move_joystick(int code,int pos);
void click(int code);
void release(int code);
void press(int code);
void sync_events();
struct input_event create_key_event(int code,int val);
extern int fd;
