/* automatically generated by rust-bindgen 0.54.1 */

extern "C" {
    pub fn open_default();
}
extern "C" {
    pub fn open_path(path: *mut ::std::os::raw::c_char);
}
extern "C" {
    pub fn destroy_device();
}
extern "C" {
    pub fn create_device();
}
extern "C" {
    pub fn setup_joystick_right_events();
}
extern "C" {
    pub fn setup_joystick_left_events();
}
extern "C" {
    pub fn setup_menupad_events();
}
extern "C" {
    pub fn setup_gamepad_north();
}
extern "C" {
    pub fn setup_gamepad_west();
}
extern "C" {
    pub fn setup_gamepad_east();
}
extern "C" {
    pub fn setup_gamepad_south();
}
extern "C" {
    pub fn setup_dpad_events();
}
extern "C" {
    pub fn move_joystick(code: ::std::os::raw::c_int, pos: ::std::os::raw::c_int);
}
extern "C" {
    pub fn click(code: ::std::os::raw::c_int);
}
extern "C" {
    pub fn release(code: ::std::os::raw::c_int);
}
extern "C" {
    pub fn press(code: ::std::os::raw::c_int);
}
extern "C" {
    pub fn sync_events();
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct input_event {
    _unused: [u8; 0],
}
extern "C" {
    pub fn create_key_event(code: ::std::os::raw::c_int, val: ::std::os::raw::c_int)
        -> input_event;
}
extern "C" {
    pub fn create_input_event(
        type_: ::std::os::raw::c_int,
        code: ::std::os::raw::c_int,
        val: ::std::os::raw::c_int,
    ) -> input_event;
}
extern "C" {
    pub static mut fd: ::std::os::raw::c_int;
}
