/* automatically generated by rust-bindgen 0.54.1 */

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct input_event {
    _unused: [u8; 0],
}
extern "C" {
    pub fn create_key_event(code: ::std::os::raw::c_int, val: ::std::os::raw::c_int)
        -> input_event;
}
extern "C" {
    pub fn create_input_event(
        type_: ::std::os::raw::c_int,
        code: ::std::os::raw::c_int,
        val: ::std::os::raw::c_int,
    ) -> input_event;
}
extern "C" {
    pub static mut fd: ::std::os::raw::c_int;
}
