[package]
name = "tetherplay-uinput"
version = "0.1.0"
authors = ["Niall Bermingham <niallbermingham4@mail.dcu.ie>", "Jordan Conway-McLaughlin <jordan.conwaymclaughlin24@mail.dcu.ie>" ]
edition = "2018"

[dependencies]
uinput = "0.1.3"
