[package]
name = "rust-uinput"
version = "0.1.0"
authors = ["Niall Bermingham <niallbermingham4@mail.dcu.ie>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
uinput = "0.1.3"
