/* automatically generated by rust-bindgen 0.54.1 */

extern "C" {
    pub fn move_joystick(
        dev: *mut libevdev_uinput,
        code: ::std::os::raw::c_int,
        pos: ::std::os::raw::c_int,
    );
}
extern "C" {
    pub fn click(dev: *mut libevdev_uinput, code: ::std::os::raw::c_int);
}
extern "C" {
    pub fn release(dev: *mut libevdev_uinput, code: ::std::os::raw::c_int);
}
extern "C" {
    pub fn press(dev: *mut libevdev_uinput, code: ::std::os::raw::c_int);
}
extern "C" {
    pub fn sync_events(dev: *mut libevdev_uinput);
}
extern "C" {
    pub fn write_key_event(
        dev: *mut libevdev_uinput,
        code: ::std::os::raw::c_int,
        value: ::std::os::raw::c_int,
    );
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct libevdev_uinput {
    _unused: [u8; 0],
}

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct libevdev {
    pub _address: u8,
}

extern "C" {
    pub fn hardcode_device(dev: *mut libevdev);
}
extern "C" {
    pub fn create_device() -> *mut libevdev_uinput;
}
extern "C" {
    pub fn cleanup(dev: *mut libevdev_uinput);
}
extern "C" {
    pub fn enable_abs_event(dev: *mut libevdev, event_code: ::std::os::raw::c_int);
}
extern "C" {
    pub fn enable_key_event(dev: *mut libevdev, event_code: ::std::os::raw::c_int);
}
extern "C" {
    pub fn enable_event(
        dev: *mut libevdev,
        type_: ::std::os::raw::c_int,
        event_code: ::std::os::raw::c_int,
    );
}
